### ISSUE TITLE
Well done!

### ISSUE THREAD

**Issue by gitseb14** [martinalebachew/Asunder#1]
Hi Martin, nice work!
It's nice to see more people digging into Classoos  and creating wonderful things!
I've created a script to be executed on an Android device that decrypts  the PDF digital textbook
I plan to post my work on github in the next couple of days (I'll add a link to this thread as soon as I'll post it) 
I wasn't able to install your extension and the decryptor for some reason, so, if you can, add some detailed instructions on how to install and configure it - it'll be awesome.
looking forward to hear back from you soon!

**Comment by martinalebachew** [comment]
Hey, sorry for the delay, I must have missed this issue 😅
This project is actually based on mobile research so I believe our code should be fairly similar,
Please let me know when you upload your code! I'm really interested.
I took a break from developing this project for the last few months, but I plan to make significant progress this month.
A big part of that is to include (and simplify) build instructions. I'll keep you updated!
Feel free to reach out on LinkedIn,
https://linkedin.com/in/martinalebachew

**Comment by BlueIncog** [comment]
> Hi Martin, nice work! It's nice to see more people digging into Classoos and creating wonderful things! I've created a script to be executed on an Android device that decrypts the PDF digital textbook I plan to post my work on github in the next couple of days (I'll add a link to this thread as soon as I'll post it) I wasn't able to install your extension and the decryptor for some reason, so, if you can, add some detailed instructions on how to install and configure it - it'll be awesome. looking forward to hear back from you soon!

Hello, would you be able to share the repository for this privately/ publicly, it would be appreciated @gitseb14
