### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by BlueIncog** [martinalebachew/Asunder#7]
Hi, would you be able to build this extension so I can use it please?

**Comment by Sprium** [comment]
To run the extension you need firstly to get a demo key from Apryse. just sign up and copy the key. than download this https://pdftron.s3.amazonaws.com/downloads/PDFNetC64.zip and get PDFNetC.dll from lib. place PDFNetC.dll inside decryptor/bin (create the folder). after that run install_asunder.py script from scripts and install to your machine whatever libs your missing. when done open chrome extensions and enable developer mode and download the extension by choosing Asunder-Extension/dist

**Comment by Sprium** [comment]
oh and put your apryse key inside src/pdf.hpp

**Comment by martinalebachew** [comment]
@Sprium Thanks! the install_asunder.py actually simplifies most of the building process.

To install Asunder from source, follow these steps:
1. Get your key from [Apryse Developer Portal](https://dev.apryse.com/). Copy it into src/pdf.hpp.
2. Install the prerequisites for your operating system. Those include OpenSSL, Node.js, CMake and vcpkg. On Windows, make sure you have the latest version of Visual Studio installed. On macOS, make sure you have the XCode developer tools installed. On Linux, make sure you have make and gcc installed.
3. Add vcpkg to path and install the following packages: curl, nlohmann-json and boost-filesystem. If you are using Windows, you will currently need to manually set the host triplet as x64-windows for each of those packages.
4. Run scripts/install_asunder.py.
5. Manually load the extension into Chrome, further instructions will appear after compilation is done.

This should cover all of it, I'll work on more detailed build instructions in the near future :)
Let me know if you encounter any issue!

* Note that the extension currently supports only the Israeli version of Classoos, and works only with Chrome.
